version: 2.1
jobs:
  create_infrastructure: 
    docker: 
      - 
        image: amazon/aws-cli
    steps: 
      - checkout
      - 
        run:
          name: "Create Cloudformation Stack"
          command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
      - 
        run:
          name: "Create Cloudformation Stack"
          command: |  
              aws cloudformation describe-stack-events --stack-name myStack-a3c2c
     
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
